[pytest]
testpaths = tests/unit tests/integration
python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_*
addopts = -v --alluredir=./allure-results
allure_report_polish = false
allure_show_duplicates = true

markers =
    P0: P0优先级case
    P1: P1优先级case
    P2: P2优先级case

    Api: api接口
    Rpc: rpc接口请求

    E2E: end to end